name: Docker Python Test

on:
  push:
   branch:
    - docker-py

jobs:
  Build:
    runs-on: ubuntu-latest
    steps:
      - name: Get Code
        uses: actions/checkout@v3
      - name: Run Docker with Python
        uses: ./.github/docker
      - name: Explore Docker with Python
        run: echo "Explore Docker with Python"